### ISSUE TITLE
Problem replacing "Times.Never" expressions

### ISSUE THREAD

**Issue by yor-so** [samsmithnz/MoqToNSubstituteConverter#24]
Input:
`mock.Verify(x => x.Method(It.IsAny<int>(), It.IsAny<int>()), Times.Never);`

Current output:
`mock.Received().Method(Arg.Any<int>(), Arg.Any<int>()), Times.Never;`

Expected output:
`mock.DidNotReceive().Method(Arg.Any<int>(), Arg.Any<int>());`

From https://github.com/AlbertoMonteiro/moq-to-nsubstitute repo, the regex substitution that works is:

Find: `(?<!\.)\b(\w+)\.Verify\((\w+) => \2(.+?), Times\.Never\)`
Replace: `$1.DidNotReceive()$3`

**Comment by yor-so** [comment]
I found that the the method Conversion.ProcessVerify validates for expressions with Times.Exactly and Times.Once, but not for Times.Never. I send a similar fix in another repo here: https://github.com/dylan-asos/moq-to-nsub/pull/3/commits/419db9e79b729d635d894254c3c727b7700e12f1

**Comment by samsmithnz** [comment]
Thanks @yor-so. Pushed a fix just now.
