### ISSUE TITLE
Mock variables/fields constructed with new() are not converted

### ISSUE THREAD

**Issue by jeroenwalter** [samsmithnz/MoqToNSubstituteConverter#26]
This field  or vairable is not converted to a `Substitute.For<>`

`Mock<IConfiguration> mockConfiguration = new ();`

**Comment by samsmithnz** [comment]
This is an interesting case, I think the converted result should be:

`IConfiguration mockConfiguration = Substitute.For<IConfiguration>()`?

Does that look correct?

**Comment by jeroenwalter** [comment]
Jup :)
