### ISSUE TITLE
Raising events is not converted

### ISSUE THREAD

**Issue by jeroenwalter** [samsmithnz/MoqToNSubstituteConverter#27]
For instance, `_connectionStateMock.Raise(m => m.Connected += default, default, default);` should be converted to something like
`_connectionStateMock.Connected += Raise.EventWith()`

**Comment by samsmithnz** [comment]
wouldn't the result actually be:
`_connectionStateMock.Connected += Raise.EventWith(default, default)` ?

The default parameters would need to be passed into the event still - did I interpret your code correctly?

**Comment by jeroenwalter** [comment]
Yes, that's why I said "something like" .:)
I'm fairly new to NSubstitute, I've just completed the conversion of one of our large projects from Moq to NSubstitute, primarily via several find and replace in all files via some regexes.

**Comment by samsmithnz** [comment]
yep - I'm relatively new to, for likely the same reasons. The raise events and callbacks are way more complex than other examples, but I'll keep chipping away at it. Thanks for opening these issues! Really helpful and appreciated.
